spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/infy_department
    password: Admin@123
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: '9001'