spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/infy_department
    password: root
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
   
server:
  port: '9001'
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost
    
    
management:
    endpoint:
        metrics:
            enabled: true
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    metrics:
        export:
            prometheus:
                enabled: true
    
    